# If you are using a dongle, custom ZMK configuration options should go in this
# file. If you are not using a dongle (using the left as central), this file is
# ignored.

# Enable persistent output selection for dongle configurations
# this _should_ prevent switching when bluetooth connections are lost
CONFIG_ZMK_OUTPUT_SELECTION_PERSIST=y
